export const CONTRACTS = {
  TOKEN: "YOUR_TOKEN_CONTRACT_ADDRESS",
  IDENTITY: "YOUR_IDENTITY_CONTRACT_ADDRESS",
  SUPPLY: "YOUR_SUPPLY_CHAIN_CONTRACT_ADDRESS",
  DISBURSEMENT: "YOUR_DISBURSEMENT_CONTRACT_ADDRESS",
};

export const NETWORK = {
  RPC_URL: "https://soroban-testnet.stellar.org",
  NETWORK_PASSPHRASE: "Test SDF Network ; September 2015",
};